variable "project" {}
variable "environment" {}
variable "region" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "availability_zone" {}
variable "ami_id" {}
variable "instance_type" {}
variable "ssh_cidr" {}
variable "extra_tags" {}
