variable "ig_id" {}
variable "public_subnet" {}
variable "public_subnet2" {}
variable "private_subnet" {}
variable "private_subnet2" {}
variable "aws_internet_gateway" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "aws_vpc" {}
variable "aws_public_subnet_cidr" {}
variable "aws_private_subnet_cidr" {}
variable "aws_availability_zone_1" {}
variable "aws_availability_zone_2" {}
variable "aws_public_subnet_cidr_2" {}
variable "aws_private_subnet_cidr_2" {}